title: Github pages tutorial
author: Marcus Beirne

description: > # this means to ignore newlines until "baseurl:"
  This is just a test to use the git hub pages
# social links
twitter_username: @marcus_beirne
github_username:  beirnem

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
